/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package br.sp.senac.e169.exemplojanelas;

import static java.awt.GridBagConstraints.BOTH;
import javax.swing.JOptionPane;

/**
 *
 * @author patrick.spereira1
 */
public class TelaPrince extends javax.swing.JFrame {

    /**
     * Creates new form TelaPrince
     */
    public TelaPrince() {
        initComponents();
        
        //centralizar a tela
        setLocationRelativeTo(null); 
        
        
        //maximizar tela
            setExtendedState(MAXIMIZED_BOTH);
       }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        btnMsgSimples = new javax.swing.JButton();
        btnEntrada = new javax.swing.JButton();
        btnConfirmacao = new javax.swing.JButton();
        btnOpcoes = new javax.swing.JButton();
        btnDialogo = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(255, 0, 255));
        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder("Atalhos"));

        btnMsgSimples.setBackground(new java.awt.Color(255, 255, 51));
        btnMsgSimples.setForeground(new java.awt.Color(0, 0, 0));
        btnMsgSimples.setText("Msg Simples");
        btnMsgSimples.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnMsgSimplesActionPerformed(evt);
            }
        });

        btnEntrada.setBackground(new java.awt.Color(255, 153, 51));
        btnEntrada.setForeground(new java.awt.Color(0, 0, 0));
        btnEntrada.setText("Entrada");
        btnEntrada.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEntradaActionPerformed(evt);
            }
        });

        btnConfirmacao.setBackground(new java.awt.Color(0, 255, 0));
        btnConfirmacao.setForeground(new java.awt.Color(0, 0, 0));
        btnConfirmacao.setText("Confirmação");
        btnConfirmacao.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnConfirmacaoActionPerformed(evt);
            }
        });

        btnOpcoes.setBackground(new java.awt.Color(153, 51, 255));
        btnOpcoes.setForeground(new java.awt.Color(0, 0, 0));
        btnOpcoes.setText("Opções");
        btnOpcoes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnOpcoesActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(btnMsgSimples, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnEntrada, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnConfirmacao, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnOpcoes, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(btnMsgSimples)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnEntrada)
                .addGap(18, 18, 18)
                .addComponent(btnConfirmacao)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnOpcoes)
                .addContainerGap(141, Short.MAX_VALUE))
        );

        btnDialogo.setBackground(new java.awt.Color(0, 153, 255));
        btnDialogo.setForeground(new java.awt.Color(0, 0, 0));
        btnDialogo.setText("Diálogo");
        btnDialogo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDialogoActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 218, Short.MAX_VALUE)
                .addComponent(btnDialogo))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(btnDialogo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnMsgSimplesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnMsgSimplesActionPerformed
    JOptionPane.showMessageDialog(rootPane, "Olá Alunos!");



    }//GEN-LAST:event_btnMsgSimplesActionPerformed

    private void btnEntradaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEntradaActionPerformed
       String nome = JOptionPane.showInputDialog(rootPane, "digite seu nome: ");
       
       if(nome.isEmpty () || nome !=null){
       JOptionPane.showMessageDialog(rootPane, "Bem-vindo(a) " + nome, "Boas-Vindas", JOptionPane.INFORMATION_MESSAGE);
        
       }
        
       
    }//GEN-LAST:event_btnEntradaActionPerformed

    private void btnConfirmacaoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnConfirmacaoActionPerformed
      int retorno = JOptionPane.showConfirmDialog(rootPane, "Deseja confirmar");
       if(retorno == 0){
           JOptionPane.showMessageDialog(rootPane, "Você clicou em Sim!");
       }else if(retorno == 1){
       JOptionPane.showMessageDialog(rootPane, "Você clicou em Não!");
    }else if(retorno == 2){
     JOptionPane.showMessageDialog(rootPane, "Você clicou em Cancelar!");   
    }
       
       
       
    }//GEN-LAST:event_btnConfirmacaoActionPerformed

    private void btnOpcoesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnOpcoesActionPerformed
     JOptionPane.showOptionDialog(rootPane,
              "Qual métrica usar?", 
              "Escolha de medidas",
              JOptionPane.DEFAULT_OPTION, 
              JOptionPane.QUESTION_MESSAGE, 
              null, 
              new String[]{"Km","milhas","polegadas", "jardas", "metros","milhas"},
              "milhas");
      





    }//GEN-LAST:event_btnOpcoesActionPerformed

    private void btnDialogoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDialogoActionPerformed
     TelaDialogo novoDialogo = new TelaDialogo(this,true);
     novoDialogo.setVisible(true);
        
        
        
        
        
        
    }//GEN-LAST:event_btnDialogoActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TelaPrince.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TelaPrince.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TelaPrince.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TelaPrince.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TelaPrince().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnConfirmacao;
    private javax.swing.JButton btnDialogo;
    private javax.swing.JButton btnEntrada;
    private javax.swing.JButton btnMsgSimples;
    private javax.swing.JButton btnOpcoes;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables
}
